name: news
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  bloc: ^8.0.3
  build_runner: ^2.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  form_validator: ^1.0.2
  get_it: ^7.2.0
  http: ^0.13.5
  intl: ^0.17.0
  random_string: ^2.3.1
  random_words: ^1.0.2
  shared_preferences: ^2.0.15
  timeago: ^3.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0

flutter:
  uses-material-design: true

  assets:
    - asset/image/

flutter_native_splash:
  color: "#595959"

flutter_icons:
  android: true
  ios: true
  image_path: "asset/image/News-1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
